<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="GS-4656" failures="2" tests="5" name="alluretest" time="0.881" errors="0" timestamp="2021-05-28T15:31:25 IST">
  <testcase classname="test.report.BaseTest" name="test1" time="0.49">
    <failure type="java.lang.AssertionError" message="expected [3] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [2]
at test.report.BaseTest.test1(BaseTest.java:9)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="test.report.BaseTest" name="test4" time="0.014">
    <failure type="java.lang.AssertionError" message="This test should be failed">
      <![CDATA[java.lang.AssertionError: This test should be failed
at test.report.BaseTest.test4(BaseTest.java:24)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
  <testcase classname="test.report.BaseTest" name="skippedByDependencyTest" time="0.0">
    <skipped/>
  </testcase> <!-- skippedByDependencyTest -->
  <testcase classname="test.report.BaseTest" name="test2" time="0.011"/>
  <testcase classname="test.report.BaseTest" name="test3" time="0.007"/>
</testsuite> <!-- alluretest -->
